export const categoriesData = [
  {
    iconClass: "bi bi-laptop",
    title: "Computer Science",
    courseCount: 24,
    link: "#",
    color: "linear-gradient(135deg, #3b82f6, #1d4ed8)",
    delay: 100,
  },
  {
    iconClass: "bi bi-briefcase",
    title: "Business",
    courseCount: 18,
    link: "#",
    color: "linear-gradient(135deg, #10b981, #047857)",
    delay: 150,
  },
  {
    iconClass: "bi bi-palette",
    title: "Design",
    courseCount: 15,
    link: "#",
    color: "linear-gradient(135deg, #8b5cf6, #6d28d9)",
    delay: 200,
  },
  {
    iconClass: "bi bi-heart-pulse",
    title: "Health & Medical",
    courseCount: 12,
    link: "#",
    color: "linear-gradient(135deg, #ef4444, #dc2626)",
    delay: 250,
  },
  {
    iconClass: "bi bi-globe",
    title: "Languages",
    courseCount: 21,
    link: "#",
    color: "linear-gradient(135deg, #f97316, #ea580c)",
    delay: 300,
  },
  {
    iconClass: "bi bi-diagram-3",
    title: "Science",
    courseCount: 16,
    link: "#",
    color: "linear-gradient(135deg, #06b6d4, #0891b2)",
    delay: 350,
  },
  {
    iconClass: "bi bi-megaphone",
    title: "Marketing",
    courseCount: 19,
    link: "#",
    color: "linear-gradient(135deg, #ec4899, #db2777)",
    delay: 100,
  },
  {
    iconClass: "bi bi-graph-up-arrow",
    title: "Finance",
    courseCount: 14,
    link: "#",
    color: "linear-gradient(135deg, #059669, #047857)",
    delay: 150,
  },
  {
    iconClass: "bi bi-camera",
    title: "Photography",
    courseCount: 11,
    link: "#",
    color: "linear-gradient(135deg, #64748b, #475569)",
    delay: 200,
  },
  {
    iconClass: "bi bi-music-note-beamed",
    title: "Music",
    courseCount: 13,
    link: "#",
    color: "linear-gradient(135deg, #7c3aed, #5b21b6)",
    delay: 250,
  },
  {
    iconClass: "bi bi-gear",
    title: "Engineering",
    courseCount: 22,
    link: "#",
    color: "linear-gradient(135deg, #6b7280, #4b5563)",
    delay: 300,
  },
  {
    iconClass: "bi bi-journal-text",
    title: "Law & Legal",
    courseCount: 9,
    link: "#",
    color: "linear-gradient(135deg, #f59e0b, #d97706)",
    delay: 350,
  },
  {
    iconClass: "bi bi-cup-hot",
    title: "Culinary Arts",
    courseCount: 8,
    link: "#",
    color: "linear-gradient(135deg, #f43f5e, #e11d48)",
    delay: 100,
  },
  {
    iconClass: "bi bi-trophy",
    title: "Sports & Fitness",
    courseCount: 17,
    link: "#",
    color: "linear-gradient(135deg, #84cc16, #65a30d)",
    delay: 150,
  },
  {
    iconClass: "bi bi-pen",
    title: "Writing",
    courseCount: 10,
    link: "#",
    color: "linear-gradient(135deg, #6366f1, #4338ca)",
    delay: 200,
  },
  {
    iconClass: "bi bi-body-text",
    title: "Psychology",
    courseCount: 12,
    link: "#",
    color: "linear-gradient(135deg, #14b8a6, #0d9488)",
    delay: 250,
  },
  {
    iconClass: "bi bi-tree",
    title: "Environment",
    courseCount: 7,
    link: "#",
    color: "linear-gradient(135deg, #22c55e, #16a34a)",
    delay: 300,
  },
  {
    iconClass: "bi bi-chat-dots",
    title: "Communication",
    courseCount: 15,
    link: "#",
    color: "linear-gradient(135deg, #0ea5e9, #0284c7)",
    delay: 350,
  },
];
